# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubredditStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subreddit_name', models.CharField(max_length=255, verbose_name='Name of Subreddit')),
                ('timestamp', models.DateField(verbose_name='Time of Stats')),
                ('time_bucket', models.CharField(max_length=127, verbose_name='Stringified List of Best Times')),
                ('weekday_bucket', models.CharField(max_length=127, verbose_name='Stringified List of Best Weekdays')),
            ],
        ),
    ]
